### PR TITLE
[385] Improve suite summaries

### LINKED ISSUE #306: Add headings / table of contents to buildings#show

### LINKED ISSUE #385: Update draw suite summary page
Use the summary from `buildings`.

### PR DESCRIPTION
**Pull request by orenyk**
Resolves #385 resolves #306
- Update draw suite summary view
- Extract suite summary from buildings index

### CODE REVIEW

**Comment by orenyk** [comment]
@esoterik np, try again?

**Comment by esoterik** [comment]
Hit a no method error trying to look at a draft draw:

2017-03-20-105725_1440x900_scrot

draw information:

```
=> #<Draw:0x00564001a91108
 id: 3,
 name: "Margot & The Nuclear So and So's Draw",
 created_at: Mon, 20 Mar 2017 14:56:38 UTC +00:00,
 updated_at: Mon, 20 Mar 2017 14:56:38 UTC +00:00,
 status: "draft",
 intent_deadline: nil,
 locked_sizes: [],
 intent_locked: false>
[2] pry(main)> d.suites
  Suite Load (0.7ms)  SELECT "suites".* FROM "suites" INNER JOIN "draws_suites" ON "suites"."id" = "draws_suites"."suite_id" WHERE "draws_suites"."draw_id" = $1  [["draw_id", 3]]
=> [#<Suite:0x0056400165e770
  id: 11,
  building_id: 2,
  number: "484",
  created_at: Mon, 20 Mar 2017 14:56:35 UTC +00:00,
  updated_at: Mon, 20 Mar 2017 14:56:35 UTC +00:00,
  size: 4,
  group_id: nil,
  medical: false>,
 #<Suite:0x0056400165e630
  id: 14,
  building_id: 2,
  number: "00194",
  created_at: Mon, 20 Mar 2017 14:56:35 UTC +00:00,
  updated_at: Mon, 20 Mar 2017 14:56:35 UTC +00:00,
  size: 2,
  group_id: nil,
  medical: false>,
 #<Suite:0x0056400165e450
  id: 15,
  building_id: 2,
  number: "277",
  created_at: Mon, 20 Mar 2017 14:56:35 UTC +00:00,
  updated_at: Mon, 20 Mar 2017 14:56:35 UTC +00:00,
  size: 3,
  group_id: nil,
  medical: false>]
```

**Comment by orenyk** [comment]
Figured it out, had to prepopulate the other sizes. Using `Hash#default`.

**Comment by orenyk** [comment]
Updated, ready for re-review. I think I also ended up including #306.

**Comment by orenyk** [comment]
Sure, I'll fix and rebase

**Comment by orenyk** [comment]
@esoterik ok?

**Pull request merged**
