### PR TITLE
[540] Add User Documentation

### LINKED ISSUE #540: User Documentation for Pilot
As a user, I'd like to have documentation on how to use Vesta.

Porting over the github pages site from my personal repository so we can host it on yalestc.github.io

### PR DESCRIPTION
**Pull request by AlanLiu96**
Resolves #540
	* Includes user documentation at /docs folder

### CODE REVIEW

**Comment by orenyk** [comment]
This doesn't look like it includes a bunch of stuff from the two Google Doc user manuals - for the pilot I think we'll just stick with those for documentation and convert them over to GitHub Pages before final release. What do you think @esoterik?

**Comment by AlanLiu96** [comment]
Oh, I didn't realize there were two user manuals. This gh-pages is based off one of them, not sure which.

**Comment by AlanLiu96** [comment]
Kk, my bad, I mistakenly thought they were both the same document. I'll update the PR in 20 mins~

**Comment by AlanLiu96** [comment]
@orenyk, [It ](https://alanliu96.github.io/Vesta-Docs/)now contains all the info from both the docs, instead of just the admin one.

**Pull request closed without merging**
