### PR TITLE
[158] Restore student draws when destroying drawless groups

### LINKED ISSUE #158: Return members of Drawless Groups to their Draws on group deletion

### PR DESCRIPTION
**Pull request by orenyk**
Resolves #158 
- Add after_destroy callback on Group for drawless groups that restores the draws for each of its members

### CODE REVIEW

**Comment by esoterik** [comment]
@orenyk did we open a PR / otherwise document the intermittent failure in that occurred here?

**Comment by orenyk** [comment]
I did not - it appears to be a race condition. I feel like we could just do `.map(&:id).sort` to get consistent results if you'd prefer.

**Comment by esoterik** [comment]
ok, I'll make that change here and merge this in

**Comment by esoterik** [comment]
ok rebased and fixed the race condition, waiting on green build to squash and merge

**Pull request merged**
